import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SimpsonsCharacters from '../components/SimpsonsCharacters'
import StyleWrapper from '../components/StyleWrapper'

const PRIMARY_COLOR = "#3b4b92"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          List example
        </h1>
        <StyleWrapper color={PRIMARY_COLOR} size={1}>
          <SimpsonsCharacters />
        </StyleWrapper>

      </main>

    </div>
  )
}
