import { MOVIE_LIST } from '../utils/movies'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Alert from '@mui/material/Alert';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';

import { useState } from 'react'

export default function Home() {
  const [search, setSearch] = useState("")
  const [year, setYear] = useState("")
  const [movies, setMovies] = useState(MOVIE_LIST)
  const [errorMessage, setErrorMessage] = useState("")

  const handleSubmit = (event) => {
    event.preventDefault();
    validateYear()
    filterMovies()
  }

  const validateYear = () => {
    //Escape early if we don't have something
    if(year.trim() === "") {
      return
    }

    if(year.trim().length !== 4) {
      setErrorMessage(`${year} is not a valid year`)
      return
    }

    setErrorMessage("")
  }

  const filterMovies = () => {
    let filteredMovieList = [...MOVIE_LIST]

    if(search.trim() !== "") {
      filteredMovieList = filteredMovieList.filter((movie) => {
        let movieName = movie.name.toLowerCase()
        let searchValue = search.trim().toLowerCase()
        if (movieName.includes(searchValue)) {
          return true
        } return false
      })
    }
    if(year.trim() !== "") {
      filteredMovieList = filteredMovieList.filter((movie) => {
        return movie.year === parseInt(year.trim())
      })
    }

    setMovies(filteredMovieList)
  }

  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography variant="h2" component="h2" style={{textAlign: "center"}}>
            Movies
          </Typography>
          <form style={{width: '100%'}} onSubmit={handleSubmit}>
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(event)=>setSearch(event.target.value)}
                  value={search}
                  
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(event)=>setYear(event.target.value)}
                  value={year}
                />
              </Grid>
              <Grid item xs={2}>
                <Button
                  type="submit"
                  variant="contained"
                >Filter</Button>
              </Grid>
              <Grid item xs={10}>
                {errorMessage !== "" && <Alert severity="error">{errorMessage}</Alert>}
              </Grid>
            </Grid>
          </form>
          {
            movies.length === 0 &&
            <Typography variant="p" component="div">
              No results, please broaden your search
            </Typography>
          }
          <List sx={{width: `100%`}}>
          { movies.map((movieData, index)=> {
              return <ListItem key={index}>
                <ListItemText>
                  <Typography variant="p" component="div">
                    {movieData.name} ({movieData.year})
                  </Typography>
                </ListItemText>
              </ListItem>
            })
          }
          </List>
        </Container>
      </main>
    </div>
  )
}
