import {useEffect, useState} from 'react'

import Head from 'next/head'

import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';

import Table from '@mui/material/Table';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';

import Paper from '@mui/material/Paper';

import Navbar from '../components/Navbar'

import { fetchAuthors, getBooks } from '../utils/api/authors';
import AuthorInfo from '../components/AuthorInfo';
import BooksTable from '../components/BooksTable';
import PopularAuthorList from '../components/PopularAuthorList';


export default function Home() {
  const [authorKey, setAuthorKey] = useState("OL23919A")

  const [authorData, setAuthorData] = useState([])
  const [booksData, setBooksData] = useState([])

  useEffect(() => {
    fetchAuthors(authorKey).then((data) => setAuthorData(data))
  }, [authorKey])

  useEffect(() => {
    getBooks(authorKey).then((data) => setBooksData(data.entries))
    console.log(booksData)
  }, [authorKey])

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Container maxWidth="md">
          <Grid container spacing={4}>
            <Grid item xs={8}>
              <Box>
                <AuthorInfo 
                  name={authorData.name}
                  birthDate={authorData.birth_date}
                  deathDate={authorData.death_date} 
                />
                <TableContainer component={Paper}>
                    <Table>
                    <TableHead>
                        <TableRow>
                        <TableCell>Books in all Languages</TableCell>
                        </TableRow>
                    </TableHead>
                    {booksData.map((book) => {
                      return <BooksTable title={book.title} />
                    })}
                    </Table>
                </TableContainer>


              </Box>
            </Grid>
            <PopularAuthorList setAuthorKey={setAuthorKey} />
          </Grid>
        </Container>
      </main>
    </div>
  )
}
