import Head from 'next/head'
import Image from 'next/image'

import Container from '@mui/material/Container'
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';

import { useState } from 'react';

import NavBar from '../components/NavBar'
import Title from '../components/Title'
import FavouriteBooks from '../components/FavouriteBooks'

const FAVOURITE_BOOKS = [
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    rating: 9
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    rating: 8
  }
]

export default function Home() {
  const [favouriteBooks, setFavouriteBooks] = useState(FAVOURITE_BOOKS)

  const [title, setTitle] = useState("")
  const [author, setAuthor] = useState("")
  const [rating, setRating] = useState("")

  const onTitleChange = (event) => {
    setTitle(event.target.value)
  }

  const onAuthorChange = (event) => {
    setAuthor(event.target.value)
  }

  const onRatingChange = (event) => {
    //Validation for number
    if(!isNaN(event.target.value) && !null ){
      setRating(event.target.value)
    }
  }

  let valuesEntered = true
  const onAddFavouriteBookClick = (event) => {
    event.preventDefault()
    //Ensures all fields have values before submitting
    if(title != "" && author != "" && rating != "") {
      let newFavouriteBook = {
        title: title,
        author: author,
        rating: parseInt(rating)
      }
      setFavouriteBooks([newFavouriteBook, ...favouriteBooks])

      setTitle("")
      setAuthor("")
      setRating("")
      valuesEntered = true
    }
    else {
      valuesEntered = false
    }
    console.log(valuesEntered)
  }

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar title={"Our Library"} />
      <main>
        <Container sx={{paddingTop: '2rem'}} maxWidth="md">
           <Paper sx={{ p: 2, display: 'flex', flexDirection: 'column', marginBottom: "2rem"}}>
              <Title>Add a New Favourite</Title>
              <form>
                <Grid container spacing={3}>
                  <Grid item xs={10} sm={5}>
                    <TextField
                      required
                      id="title"
                      name="title"
                      label="Book Title"
                      fullWidth
                      variant="standard"
                      onChange={onTitleChange}
                      value={title}
                    />
                  </Grid>
                  <Grid item xs={8} sm={3}>
                    <TextField
                      required
                      id="author"
                      name="author"
                      label="Author"
                      fullWidth
                      variant="standard"
                      onChange={onAuthorChange}
                      value={author}
                    />
                  </Grid>
                  <Grid item xs={6} sm={2}>
                    <TextField
                      required
                      id="rating"
                      name="rating"
                      label="Rating"
                      fullWidth
                      variant="standard"
                      onChange={onRatingChange}
                      value={rating}
                    />
                  </Grid>
                  <Grid item xs={2} sm={2}>
                    <Button variant="contained" sx={{ mt: 1.5, ml: 1 }}
                    onClick={onAddFavouriteBookClick}
                    >Add</Button>
                  </Grid>
                </Grid>
              </form>
           </Paper>
          <FavouriteBooks books={favouriteBooks} />
        </Container>
      </main>
    </div>
  )
}
