import Head from 'next/head'
import Image from 'next/image'

import Container from '@mui/material/Container'
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';

import { useState } from 'react';
import Alert from '@mui/material/Alert';
import { AlertTitle } from '@mui/material';

import NavBar from '../components/NavBar'
import Title from '../components/Title'
import FavouriteBooks from '../components/FavouriteBooks'

const FAVOURITE_BOOKS = [
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    rating: 9
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    rating: 8
  }
]

export default function Home() {
  //Stateful variable for favourite book array, takes constant as default
  const [favouriteBooks, setFavouriteBooks] = useState(FAVOURITE_BOOKS)

  //Stateful variable for input fields with a blank default value
  const [title, setTitle] = useState("")
  const [author, setAuthor] = useState("")
  const [rating, setRating] = useState(0)

  //Stateful boolean for the alert toggle
  const [alertActive, setAlertActive] = useState(false)

  //Handler updates the state when text field updates
  const onTitleChange = (event) => {
    setTitle(event.target.value)
  }

  const onAuthorChange = (event) => {
    setAuthor(event.target.value)
  }

  const onRatingChange = (event) => {
    setRating(event.target.value)
  }

  const onAddFavouriteBookClick = (event) => {
    //Stops the form from submitting
    event.preventDefault()
    //Ensures all fields have values before submitting
    if(title != "" && author != "" && rating != "") {
      //Creates a new book object using inputted values and adds it to the list of favourite books
      let newFavouriteBook = {
        title: title,
        author: author,
        rating: parseInt(rating)
      }
      setFavouriteBooks([newFavouriteBook, ...favouriteBooks])

      //Resets all values to default (blank)
      setTitle("")
      setAuthor("")
      setRating("")

      //Hides alert in case it's still up
      setAlertActive(false)
    }
    //If any value is missing, the alert will be active
    else {
      setAlertActive(true)
    }
  }

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar title={"Our Library"} />
      <main>
        <Container sx={{paddingTop: '2rem'}} maxWidth="md">
           <Paper sx={{ p: 2, display: 'flex', flexDirection: 'column', marginBottom: "2rem"}}>
              <Title>Add a New Favourite</Title>
              <form>
                <Grid container spacing={3}>
                  <Grid item xs={10} sm={5}>
                    <TextField
                      required
                      id="title"
                      name="title"
                      label="Book Title"
                      fullWidth
                      variant="standard"
                      //Handler runs when text field value changes and value is controlled
                      onChange={onTitleChange}
                      value={title}
                    />
                  </Grid>
                  <Grid item xs={8} sm={3}>
                    <TextField
                      required
                      id="author"
                      name="author"
                      label="Author"
                      fullWidth
                      variant="standard"
                      onChange={onAuthorChange}
                      value={author}
                    />
                  </Grid>
                  <Grid item xs={6} sm={2}>
                    <TextField
                      required
                      type="number"
                      id="rating"
                      name="rating"
                      label="Rating"
                      fullWidth
                      variant="standard"
                      onChange={onRatingChange}
                      value={rating}
                    />
                  </Grid>
                  <Grid item xs={2} sm={2}>
                    <Button variant="contained" sx={{ mt: 1.5, ml: 1 }}
                    onClick={onAddFavouriteBookClick}
                    >Add</Button>
                  </Grid>
                </Grid>
                { //If the alert active variable is true (check validation), Alert appears
                  alertActive && 
                  <Alert severity="error">
                    <AlertTitle>Error</AlertTitle>
                    Please enter all values correctly.</Alert>
                }
              </form>
           </Paper>
          {/* Uses imported favourite books component and submits the favourite book list as a prop */}
          <FavouriteBooks 
            books={favouriteBooks}
            // title={title} 
            // author={author}
            // rating={rating}
          />
        </Container>
      </main>
    </div>
  )
}
