import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import Button from 'react-bootstrap/Button'

import ComponentsLibrariesList from '../components/ComponentsLibrariesList'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <h1>
            React Bootstrap Example
          </h1>
          <Row>
            <Col>
              <h3>List of libraries to look at</h3>
              <ComponentsLibrariesList />
            </Col>
            <Col>
              <Button variant="info">Example</Button>
            </Col>
          </Row>
        </Container>
        

      </main>
    </div>
  )
}
