import Head from 'next/head'
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Box>
            <Typography variant="h2">
              Welcome to using MUI!
            </Typography>
            <Typography variant="p">
              This is an example of using material UI
            </Typography>
            <Button variant="contained">Click me</Button>
          </Box>
        </Container>
        
      </main>
    </div>
  )
}
